config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  #application
  get '/about', to:'application#about'
  # users
  get '/user_profile/:id', to: 'users#show', as: 'user_profile'
  resources :users do
    member do
      get :confirm_email
    end
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  put '/users/forgot', to: 'users#update'

  # sessions
  get '/signin', to: 'sessions#new'
  get '/sessions/new', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  patch '/signin', to: 'sessions#new'

  # Omniauth
  get '/auth/:provider/callback', to: 'sessions#create'

  # password_resets
  resources :password_resets

  # books
  # has to be outside books block, was not routing properly
  get '/books/search', to: 'books#search', as: 'book_search'
  resources :books do
    resources :chapters
  end
end

app/controllers/password_resets_controller.rb
# PasswordResetsController
class PasswordResetsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    flash[:message] = 'Email sent with password reset instructions.'
    redirect_to root_url
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])

    if @user.password_reset_sent_at < 2.hours.ago
      flash[:message] = 'Password reset has expired.'
      redirect_to new_password_reset_path
    elsif @user.update_attributes(params.require(:user).permit(:password,
                                                               :password_confirmation))
      flash[:message] = 'Password has been reset!'
      redirect_to root_url
    else
      render :edit
    end
  end
end

app/views/password_resets/edit.html.erb
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="group">
    <%= f.label :password, class: "label" %>
    <%= f.password_field :password, class: "input" %>
  </div>
  <div class="group">
    <%= f.label :password_confirmation, class: "label" %>
    <%= f.password_field :password_confirmation, class: "input" %>
  </div>
  <div class="actions">
    <%= f.submit "Update Password", class: "button" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<div class="login-wrap">
  <div class="login-html">
    <div class="login-form">
       <%= form_tag password_resets_path, :method => :post do %>
          <div class="group">
            We will send you an email to reset your password</br></br></br>
          </div>
          <div class="group">
            <%= label_tag :email, 'Email', class: "label" %>
            <%= email_field_tag :email, "", class: "input" %>
          </div>
          <div class="group">
              <%= submit_tag "Enter", class: "button" %>
          </div>
          <div class="hr"></div>
        <% end %>
      </div>
    </div>
  </div>
</div>