config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  #application
  get '/about', to:'application#about'
  # users
  get '/user_profile/:id', to: 'users#show', as: 'user_profile'
  resources :users do
    member do
      get :confirm_email
    end
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  put '/users/forgot', to: 'users#update'

  # sessions
  get '/signin', to: 'sessions#new'
  get '/sessions/new', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  patch '/signin', to: 'sessions#new'

  # Omniauth
  get '/auth/:provider/callback', to: 'sessions#create'

  # password_resets
  resources :password_resets

  # books
  # has to be outside books block, was not routing properly
  get '/books/search', to: 'books#search', as: 'book_search'
  resources :books do
    resources :chapters
  end
end

app/models/book.rb
# Book
class Book < ApplicationRecord
  has_many :chapters

  # paperclip
  has_attached_file :cover_image,
                    styles: { medium: '300x300', thumb: '75x150' },
                    default_url: ''

  validates_attachment_content_type :cover_image, content_type: %r{\Aimage\/.*\z}

  validates_presence_of :title, :book_code

  validates :title, length: { in: 3..256 }
  validates :book_code, length: { in: 3..80 },
                        uniqueness: { case_sensitive: false }

  validates :description, length: { maximum: 500 },
                          allow_blank: true

  # scopes (chainable class methods)
  # have the if <>.present? on any input
  # you will have to override this order with reorder(colum: :direction)
  default_scope { order(created_at: :desc) }

  scope :by_book_code, ->(book_code) { where(book_code: book_code) if book_code.present? }
  # search by title, made to be case insensitive
  scope :by_title, ->(title) { where('UPPER(title) LIKE UPPER(?)', "%#{title}%") if title.present? }

  # should these be moved?
  scope :order_by_title_asc, -> { reorder(title: :asc) }
  scope :order_by_title_desc, -> { reorder(title: :desc) }
end

app/controllers/books_controller.rb
# BooksController
class BooksController < ApplicationController
  include BasicJson

  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = Book.all
    render_json_and_html(@books)
  end

  def show
    render_json_and_html(@book)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy if @book
    redirect_to books_path
  end

  def search
    @books = Book.by_title(params[:query])
    render_json_and_html(@books)
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(
      :title,
      :book_code,
      :description,
      :cover_image,
      chapter_attributes: []
    )
  end
end

app/views/books/_book.html.erb
<div class="book" style="background-image: url(<%= book.cover_image.url(:medium) %>)" data-bookimg="<%= book.cover_image.url(:medium) %>">
  <a href="<%= book_path(book) %>" aria-label="<%= book.title %> table of contents">
    <h3><%= book.title %></h3>
  </a>
  <% if logged_in? && current_user.try(:admin?) %>
    <div class="book-options">
      <%= link_to 'Edit', edit_book_path(book) %> |
      <%= link_to 'Delete', book_path(book), method: :delete %>
    </div>
  <% end %>
</div>

app/views/books/_bookform.html.erb
<div class="panel">
  <%= render partial: 'shared/error_messages', locals: { target: @book } %>
  
  <div class="">
    <%= form_for @book do |f| %>
      <div class="space-1">
        <%= f.text_field :title, class: "decorative-input", placeholder: "Book title", "aria-label": "Book Title" %>
      </div>
      <div class="space-1">
        <%= f.text_field :book_code, class: "decorative-input", placeholder: "Book code", "aria-label": "Book Code" %>
      </div>
      <div class="space-1">
        <%= f.text_area :description, class: "decorative-input book-description", placeholder: "Description", "aria-label": "Book Description" %>
      </div>
      <div class="space-1">
        <fieldset class="cover-image">
          <legend>Cover Image</legend>
          <%= f.file_field :cover_image, accept: 'image/png, image/jpeg' %>
        </fieldset>
        <div class="cover-image-pic">
          <%= image_tag(@book.cover_image.url(:medium)) %>
        </div>
      </div>
      <div class="space-1">
        <%= f.submit class: 'submit-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/books.html.erb
<p> Books to read </p>

app/views/books/edit.html.erb
<%= render 'bookform' %>
<%= link_to 'Back to Books', books_path %>

app/views/books/index.html.erb
<div class="row">
  <% if logged_in? && current_user.try(:admin?) %>
    <div class="text-center">
      <a href="<%= new_book_path %>">
        <button type="button" class="btn btn-default">Create Book</button>
      </a>
    </div>
  <% end %>
  <!-- <div class="col-sm-10">
    <%= form_tag("/books/search", method: 'get') do %>
      <%= text_field_tag :query, nil, placeholder: 'Search Books...', class: 'decorative-input' %>
      <%= submit_tag 'Search', name: '', class: 'btn btn-default' %>
    <% end %>
  </div> -->
</div>
<div class="row">
  <% @books.each do |book| %>
    <div class="col-sm-2 books"><%= render partial: 'book', locals: { book: book } %></div>
  <% end %>
</div>

app/views/books/new.html.erb
<%= render 'bookform' %>
<%= link_to 'Back to Books', books_path %>

app/views/books/search.html.erb
<a href="<%= new_book_path %>">
  <button type="button" class="btn-book-new">Create Book</button>
</a>
<div class="book-search">
  <%= form_tag("/books/search", method: 'get') do %>
    <%= text_field_tag :query, nil, placeholder: 'Search Books...', class: 'search-bar' %>
    <%= submit_tag 'Search', name: '', class: 'search-submit' %>
  <% end %>
</div>
<div class="books-container">
  <% @books.each do |book| %>
    <%= render partial: 'book', locals: { book: book } %>
  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to 'Back to Books', books_path %> <%= link_to 'Create Chapter', new_book_chapter_path(@book) %>
<div>
  <%= render partial: 'book', locals: { book: @book } %>
</div>
<div>
  <%= render partial: 'chapters/chapterlist', locals: { chapters: @book.chapters } %>
</div>