config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  #application
  get '/about', to:'application#about'
  # users
  get '/user_profile/:id', to: 'users#show', as: 'user_profile'
  resources :users do
    member do
      get :confirm_email
    end
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  put '/users/forgot', to: 'users#update'

  # sessions
  get '/signin', to: 'sessions#new'
  get '/sessions/new', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  patch '/signin', to: 'sessions#new'

  # Omniauth
  get '/auth/:provider/callback', to: 'sessions#create'

  # password_resets
  resources :password_resets

  # books
  # has to be outside books block, was not routing properly
  get '/books/search', to: 'books#search', as: 'book_search'
  resources :books do
    resources :chapters
  end
end

app/models/chapter.rb
# Chapter
class Chapter < ApplicationRecord
  # counter_cache use the chapters_count column in table
  # only works for newly added/removed records, have to recalc
  # if existing records
  # use following Book.find_each { |c| Book.reset_counters(c.id, :chapters)}
  # this will update to correct values
  belongs_to :book, dependent: :destroy, counter_cache: true

  validates_presence_of :chapter_number, :release_date, :content

  # overwrite param from id to chapter_number
  # due to rails router bug, have to
  # book_chapter_path(@book, @chapter.chapter_number) for it to properly work
  # else it throws nomethoderror .emtpy?
  # to_param still correctly
  # sets url route /books/:book_id/chapters/:chapter_number
  def to_param
    chapter_number
  end
end

app/controllers/chapters_controller.rb
# ChaptersController
class ChaptersController < ApplicationController
  include BasicJson

  before_action :set_chapter, only: %i[show edit update destroy]

  def index
    @chapters = Chapter.all
    render_json_and_html(@chapter)
  end

  def show
    @book = Book.find_by_id(params[:book_id])
    render_json_and_html(@chapter)
  end

  def new
    @chapter = Chapter.new(book_id: params[:book_id])
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to book_chapter_path(@chapter.book_id, @chapter.chapter_number)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @chapter.update(chapter_params)
      redirect_to book_chapter_path(@chapter.book_id, @chapter.chapter_number)
    else
      render :edit
    end
  end

  def destroy
    bookid = @chapter.book_id
    @chapter.destroy if @chapter
    redirect_to book_chapters_path(bookid)
  end

  private

  def set_chapter
    @chapter = Chapter.find_by(book_id: params[:book_id],
                               chapter_number: params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(
      :chapter_title,
      :book_id,
      :language,
      :status,
      :release_date,
      :content,
      :chapter_number
    )
  end
end

app/views/chapters/_chapterform.html.erb
<div class="panel">
  <%= render partial: 'shared/error_messages', locals: { target: @chapter } %>

  <div class="">
    <%= form_for(@chapter, url: { action: formaction }) do |f| %>
      <div class="space-1">
        <%= f.text_field :chapter_title, class: "decorative-input", placeholder: "Chapter title", "aria-label": "Chapter Title" %>
      </div>
      <div class="space-1">
        <%= f.text_field :language, class: "decorative-input", placeholder: "Language", "aria-label": "Select Language" %>
      </div>
      <div class="space-1">
        <%= f.text_field :status, class: "decorative-input", placeholder: "Chapter status", "aria-label": "Chapter status" %>
      </div>
      <div class="space-1">
        <%= f.date_field :release_date, class: "decorative-input", placeholder: "Chapter release date", "aria-label": "Chapter release date" %>
      </div>
      <div class="space-1">
        <%= f.number_field :chapter_number, class: "decorative-input", placeholder: "Chapter number", "aria-label": "Chapter number" %>
      </div>
      <div class="space-1">
        <%= f.text_area :content, class: "decorative-input", placeholder: "Chapter content", "aria-label": "Chapter content" %>
      </div>
      <div class="space-1">
        <%= f.hidden_field :book_id, class: "decorative-input", value: @chapter.book_id %>
      </div>
      <div class="space-1">
        <%= f.submit class: 'submit-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/chapters/_chapterlist.html.erb
<ul>
  <% chapters.each do |chapter| %>
    <li>
      <%= link_to "#{chapter.chapter_number} - #{chapter.chapter_title}", book_chapter_path(chapter.book_id, chapter.chapter_number) %>
      <%= link_to 'edit', edit_book_chapter_path(chapter.book_id, chapter.chapter_number) %>
      <%= link_to 'delete', book_chapter_path(chapter.book_id, chapter.chapter_number), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/chapters/_chapternav.html.erb
<div class="chapter-nav">
  <% if @chapter.chapter_number > 1 %>
    <a href="<%= "/books/#{@chapter.book_id}/chapters/#{@chapter.chapter_number - 1}" %>">Prev Chapter</a>
  <% end %>
  <% if @chapter.chapter_number < @book.chapters.size %>
    <%= link_to 'Next Chapter »', book_chapter_path(@chapter.book_id, @chapter.chapter_number + 1), style: 'float:right;' %>
  <% end %>
</div>

app/views/chapters/edit.html.erb
<%= render partial: 'chapterform', locals: { :formaction => 'update' } %>
<%= link_to 'Back to Chapters', book_chapters_path %>

app/views/chapters/index.html.erb
<%= link_to 'Back to Books', books_path %> <%= link_to 'Back to Index', book_path(@chapters[0].book_id) %> <%= link_to 'Create Chapter', new_book_chapter_path(@chapters[0].book_id) %>
<%= render 'chapterlist', chapters: @chapters %>

app/views/chapters/new.html.erb
<%= render partial: 'chapterform', locals: { :formaction => 'create' } %>
<%= link_to 'Back to Chapters', book_chapters_path %>

app/views/chapters/show.html.erb
<%= link_to 'All Books', books_path %> <%= link_to "Back to Index", "/books/#{params[:book_id]}" %>
<article>
  <header>
    <h1><%= link_to @book.title, book_path(@book) %> : Chapter <%= @chapter.chapter_number %></h1>
      <%= render 'chapternav' %>
  </header>
  <p class="chapter-content">
    <%= @chapter.content %>
  </p>
  <footer>
    <%= render 'chapternav' %>
  </footer>
</article>