config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  #application
  get '/about', to:'application#about'
  # users
  get '/user_profile/:id', to: 'users#show', as: 'user_profile'
  resources :users do
    member do
      get :confirm_email
    end
  end

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  put '/users/forgot', to: 'users#update'

  # sessions
  get '/signin', to: 'sessions#new'
  get '/sessions/new', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  patch '/signin', to: 'sessions#new'

  # Omniauth
  get '/auth/:provider/callback', to: 'sessions#create'

  # password_resets
  resources :password_resets

  # books
  # has to be outside books block, was not routing properly
  get '/books/search', to: 'books#search', as: 'book_search'
  resources :books do
    resources :chapters
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" id="test">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand logo" href="#">Bookworm</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        
          <li class="active"><%= link_to 'About us', root_path %></li>
          <li><%= link_to 'Read', books_path %></li>
          <li><a href="#" rel="nofollow">Write</a></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !logged_in? %>
            <li><a href="/signin">Sigin / Signup</a></li>
          <% else %>
            <li><a href="/profile"><%= current_user.name %></a></li>
            <li><%= link_to 'Sign out', logout_path, method: :delete, class: "hello" %></li>
          <% end %>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Bookworm" %></title>
<%= render 'layouts/metatags/defaultmeta' %><%= csrf_meta_tags %>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<%= stylesheet_link_tag 'application' %><% if content_for?(:js_top) %><%= yeild(:js_top) %><% end %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head><body>
<%= render 'layouts/navbar' %>

<div class="box">
  <div class="container-1">
    <input type="search" id="search" placeholder="Search..." />
    <button class="icon"><i class="fa fa-search"></i></button>
  </div>
</div>

<div class="container" id="frame">
  <div class="row">
    <%= yield %>
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" charset="utf-8"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" charset="utf-8"></script>
<%= javascript_include_tag 'application' %><% if content_for?(:js_bot) %><%= yeild(:js_bot) %><% end %>

<div id="foot_centered"> 
        <div id= "private_policy">private policy</div> 
        <div id= "foot">©2017 Bookworm - All Rights Reserved</div>
</div>
</body></html>